import { Inter, Lexend
 } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/context/CartContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <head><link rel="stylesheet" href="https://rsms.me/inter/inter.css"/></head>
      <body className={inter.className}>
        <CartProvider>
        {children}
        </CartProvider>
        </body>
    </html>
  );
}
